// lib/init/scaffold.js — write the project-side files that `flow init`
// produces: flow.config.yaml, docs/flow/* dirs + sprint.yaml, and the
// install-state.json record.
//
// All file writes are gated by `opts.dryRun` so the orchestrator can
// print the plan + skip execution in tests / preview mode. Each writer
// returns the path it would write (whether or not it actually did) so
// the caller can show a manifest.

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';

const PROJECT_DIRS_REL = Object.freeze([
  join('docs', 'flow'),
  join('docs', 'flow', 'stories'),
  join('docs', 'flow', 'journeys'),
  join('docs', 'flow', 'retros'),
  join('docs', 'flow', 'archive'),
]);

const FLOW_CONFIG_REL = 'flow.config.yaml';
const SPRINT_REL = join('docs', 'flow', 'sprint.yaml');
const STATE_REL = join('.claude', 'flow', 'install-state.json');
const FLOW_CONFIG_PROJECT_REL = join('.claude', 'flow.config.yaml');

/**
 * @typedef {Object} ScaffoldPlan
 * @property {string} cwd
 * @property {string} profile
 * @property {Object} answers - Answers from questions.js (or pre-populated)
 * @property {Object} resolvedProfile - profile after resolveProfile(catalog, profile)
 * @property {Object} catalog
 * @property {string} flowVersion
 * @property {Object} [upstreamResults] - keyed by upstream id (bmad/ecc/caveman) → InstallResult
 * @property {Object} [migrationResult] - migrate-bmad.js result, if migration ran
 */

/**
 * Plain-object render of flow.config.yaml. Hand-rolled rather than
 * templated — Handlebars-style conditionals in the .tmpl file are not
 * worth dragging in a template engine for one file, and the field set
 * is narrow enough to spell out in JS.
 *
 * @param {ScaffoldPlan} plan
 * @returns {Object} - safe to stringifyYaml directly
 */
export function buildFlowConfig(plan) {
  const config = {
    version: 1,
    generated: new Date().toISOString().slice(0, 10),
    flow_version: plan.flowVersion,
    mode: plan.profile,
    sprint_file: 'docs/flow/sprint.yaml',
    stories_dir: 'docs/flow/stories',
    journeys_dir: 'docs/flow/journeys',
    retros_dir: 'docs/flow/retros',
    archive_dir: 'docs/flow/archive',
    deferred_file: 'docs/flow/deferred.md',
    artifacts_dir: 'docs/flow/artifacts',
    adapters: {
      issue_tracker: plan.answers.issueTracker || 'none',
      pr: plan.answers.pr || 'none',
      e2e: plan.answers.e2e || 'none',
      verify: plan.answers.verify || 'custom',
    },
    integrations: {},
    review: {
      use_separate_model: plan.profile === 'team',
      auto_hard_review_tags: ['auth', 'payments', 'migration', 'pii', 'security'],
      language_reviewer: null,
      barrier_timeout_seconds: 900,
    },
    pr: { auto_merge_wait_seconds: 90 },
    implement: {
      default: 'prp-implement',
      use_tdd: plan.profile === 'standard' || plan.profile === 'team',
      e2e_auto_trigger_tags: ['ui', 'e2e', 'marketing', 'navigation'],
      docs_auto_trigger: plan.profile === 'team',
    },
    secrets: { store: plan.answers.secretsStore || 'env-file' },
    reference_docs: [],
    upstreams: {
      bmad: { installed: !!plan.upstreamResults?.bmad?.ok, subset: plan.answers.bmadSubset || 'none' },
      ecc: {
        installed: !!plan.upstreamResults?.ecc?.ok,
        subset: plan.answers.eccSubset || 'none',
        install_scope: plan.answers.eccScope || 'user',
      },
      caveman: { installed: !!plan.upstreamResults?.caveman?.ok, subset: plan.answers.cavemanSubset || 'full' },
    },
  };
  return config;
}

/**
 * Write all project-side files. Returns a manifest of what was (or
 * would be) written, plus a list of skipped paths (e.g. flow.config.yaml
 * that already existed and --force was not passed).
 *
 * @param {ScaffoldPlan} plan
 * @param {Object} [opts]
 * @param {boolean} [opts.dryRun=false]
 * @param {boolean} [opts.force=false] - overwrite existing files
 * @returns {{written: string[], skipped: string[], dirs: string[]}}
 */
export function scaffold(plan, opts = {}) {
  const written = [];
  const skipped = [];
  const dirs = [];

  // 1. Project dirs.
  for (const rel of PROJECT_DIRS_REL) {
    const abs = join(plan.cwd, rel);
    if (!existsSync(abs)) {
      if (!opts.dryRun) mkdirSync(abs, { recursive: true });
      dirs.push(abs);
    }
  }

  // 2. flow.config.yaml at .claude/flow.config.yaml (canonical) and
  //    project-root fallback honored by old code paths.
  const configPath = join(plan.cwd, FLOW_CONFIG_PROJECT_REL);
  const legacyConfigPath = join(plan.cwd, FLOW_CONFIG_REL);
  const existingConfig = existsSync(configPath) || existsSync(legacyConfigPath);
  if (existingConfig && !opts.force) {
    skipped.push(configPath);
  } else {
    const config = buildFlowConfig(plan);
    const yamlText = `# Flow project configuration — generated by \`flow init\`.\n# Edit by hand for non-standard tweaks; re-run \`flow init --update\` to refresh.\n\n${stringifyYaml(config)}`;
    if (!opts.dryRun) {
      mkdirSync(dirname(configPath), { recursive: true });
      writeFileSync(configPath, yamlText);
    }
    written.push(configPath);
  }

  // 3. docs/flow/sprint.yaml — only when migration didn't already write one.
  const sprintPath = join(plan.cwd, SPRINT_REL);
  if (existsSync(sprintPath) && !opts.force) {
    skipped.push(sprintPath);
  } else {
    const sprintYaml = stringifyYaml({
      version: 1,
      project: plan.answers.projectName || 'unnamed',
      generated: new Date().toISOString().slice(0, 10),
      last_updated: new Date().toISOString(),
      epics: [],
      stories: [],
    });
    if (!opts.dryRun) writeFileSync(sprintPath, sprintYaml);
    written.push(sprintPath);
  }

  // 4. docs/flow/deferred.md — empty header.
  const deferredPath = join(plan.cwd, 'docs', 'flow', 'deferred.md');
  if (!existsSync(deferredPath)) {
    if (!opts.dryRun) writeFileSync(deferredPath, '# Deferred work\n\nOne `-` bullet per item. Mark resolved with `[x]`.\n');
    written.push(deferredPath);
  }

  // 5. install-state.json — under ~/.claude/flow/ OR project-scope
  //    .claude/flow/. We use the project-scope path by default so the
  //    state file ships with the repo. Home-scope state is the doctor
  //    repair record path; project-scope is the canonical record.
  const statePath = join(plan.cwd, STATE_REL);
  const state = {
    schema_version: 'flow.install.v1',
    flow_version: plan.flowVersion,
    profile: plan.profile,
    answers: plan.answers,
    upstreams: extractUpstreamRecords(plan),
    migration: plan.migrationResult ? plan.migrationResult.stateRecord : null,
    ran_at: new Date().toISOString(),
  };
  if (!opts.dryRun) {
    mkdirSync(dirname(statePath), { recursive: true });
    writeFileSync(statePath, JSON.stringify(state, null, 2));
  }
  written.push(statePath);

  return { written, skipped, dirs };
}

function extractUpstreamRecords(plan) {
  const out = {};
  if (plan.upstreamResults?.bmad?.stateRecord) out.bmad = plan.upstreamResults.bmad.stateRecord;
  if (plan.upstreamResults?.ecc?.stateRecord) out.ecc = plan.upstreamResults.ecc.stateRecord;
  if (plan.upstreamResults?.caveman?.stateRecord) out.caveman = plan.upstreamResults.caveman.stateRecord;
  return out;
}
